joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min  : 0.5
      linear_forward_max  : 4.0
      linear_backward_min : 0.5
      linear_backward_max : 4.0
      angular_min : 0.7
      angular_max : 20.0
      steps       : 3